### PR TITLE
Add registration contact details

### PR DESCRIPTION
**Pull request by symroe**
This depends on https://github.com/DemocracyClub/UK-Polling-Stations/pull/2743 being merged.

Adds a new nullable key to the response for the registration contact details, if different to the electoral services contact details.

### CODE REVIEW

**Comment by symroe** [comment]
@chris48s if you have any time to give reckons on this it would be welcome. I'm keen not to alter the response too much, meaning existing clients shouldn't need to change their code (unless they need registration details of course)

**Comment by symroe** [comment]
> Instead of making the registration key nullable, why not double-up the electoral services contact info if they are the same. i.e: registration is always populated but sometimes both registration and electoral_services have the same info in them and sometimes they are different. Then as an API consumer if I want to show the user about registration, I can just look at the registration object.

Interesting. I was thinking that this might make things _harder_ for consumers. As the majority case is that the contact details are the same it would make sence to me to have a combined block titled something like "contact your council for all questions", and then if there is a registration field simply say "for X contact [], for Y contact []". 

If there are always keys, the API consumer will have to check if the details are the same, and optionally show the different statements. Maybe this is reasonable, and I agree it's nice to keep the interface the same in all cases. (And this might force people to deal with the VJB edge case better).

**Comment by symroe** [comment]
> In general, I think the key thing with making API changes is making sure they are communicated to users. What I've done in the past is made all the changes to the API that we're going to make this election cycle, keep a note of them. Then at some point before the next election do a strategically timed mailout to everyone we've dished out an API key to explaining the changes but also functioning as a "hello wave we still exist. Elections are happening soon" prod and I think that worked fairly well. Since the 2019 GE, there are now quite a lot more people on that list.

Yes, this is great. I'll start a doc now and make a note to email the list come ~Jan :+1:

**Comment by chris48s** [comment]
> If there are always keys, the API consumer will have to check if the details are the same, and optionally show the different statements


That's an interesting point - if you care about both, you need to de-dupe them.

My thought was that most API consumers are either making something around registration (e.g: https://postalvote.labour.org.uk/ ) or a thing around turnout (e.g: http://pollingstationfinder.labour.org.uk/ ) but not generally both in the same application. Of couse, the big exception to this is the Electoral Commission and they are a somewhat important consumer :)

**Pull request merged**
